import Property from './components/Board/Property.js';
import Corner from './components/Board/Corner.js';
import Exuse_Me_Blue from './assets/Exuse_Me_Blue.png';
import Dining from './assets/Dining1.png';
import Powell from './assets/POWELL.png';
import FinAid from './assets/Financial_Aid.png';
import Exuse_Me_Yellow from './assets/Exuse_Me_Yellow.png';
import Concert from './assets/Concert.png';
import USAC from './assets/USAC.png';
import Exuse_Me_Red from './assets/Exuse_Me_Red.png';
import Royce from './assets/Royce.png';
import Go from './assets/GO.png';
import Jail from './assets/JAIL.png';
import GoToJail from './assets/GO_TO_JAIL.png';
import NoFreeParking from './assets/FREE_PARKING.png';

let API_URL = "http://localhost:3000"
let majors = ["Aerospace Engineering",
    "African American Studies",
    "African and Middle Eastern Studies",
    "American Indian Studies",
    "American Literature and Culture",
    "Ancient Near East and Egyptology",
    "Anthropology",
    "Applied Linguistics",
    "Applied Mathematics",
    "Arabic",
    "Architectural Studies",
    "Art",
    "Art History",
    "Asian American Studies",
    "Asian Humanities",
    "Asian Languages and Linguistics",
    "Asian Studies",
    "Asian Religions",
    "Atmospheric and Oceanic Sciences",
    "Atmospheric and Oceanic Sciences/Mathematics",
    "Astrophysics",
    "Biochemistry",
    "Bioengineering",
    "Biology",
    "Biophysics",
    "Business Economics",
    "Central and East European Languages and Cultures",
    "Chemical Engineering",
    "Chemistry",
    "Chemistry/Materials Science",
    "Chicana and Chicano Studies",
    "Chinese",
    "Classical Civilization",
    "Climate Science",
    "Civil Engineering",
    "Cognitive Science",
    "Communication",
    "Comparative Literature",
    "Computational and Systems Biology",
    "Computer Engineering",
    "Computer Science",
    "Computer Science and Engineering",
    "Computer Engineering",
    "Dance",
    "Data Theory",
    "Design | Media Arts",
    "Earth and Environmental Science",
    "Ecology, Behavior, and Evolution",
    "Economics",
    "Education and Social Transformation",
    "Electrical Engineering",
    "Engineering Geology",
    "English",
    "Environmental Science",
    "Ethnomusicology",
    "European Studies",
    "Film & Television",
    "Financial Actuarial Mathematics",
    "French",
    "French and Linguistics",
    "Gender Studies",
    "General Chemistry",
    "Geography",
    "Geography/Environmental Studies",
    "Geology",
    "Geophysics",
    "German",
    "Global Jazz Studies",
    "Global Studies",
    "Greek",
    "Greek and Latin",
    "History",
    "Human Biology and Society",
    "Individual Field BA Arts and Architecture",
    "Individual Field BA Theater, Film, and Television",
    "Individual Field of Concentration",
    "International Development Studies",
    "Iranian Studies",
    "Italian",
    "Italian and Special Fields",
    "Jewish Studies",
    "Korean",
    "Labor Studies",
    "Latin",
    "Latin American Studies",
    "Linguistics",
    "Linguistics and Anthropology",
    "Linguistics & Asian Languages & Cultures",
    "Linguistics and Computer Science",
    "Linguistics and English",
    "Linguistics and French",
    "Linguistics and Italian",
    "Linguistics and Philosophy",
    "Linguistics and Psychology",
    "Linguistics and Scandinavian Languages",
    "Linguistics and Spanish",
    "Manufacturing Engineering",
    "Marine Biology",
    "Materials Engineering",
    "Mathematics/Applied Science",
    "Mathematics/Economics",
    "Mathematics for Teaching",
    "Mathematics of Computation",
    "Mechanical Engineering",
    "Microbiology, Immunology, and Molecular Genetics",
    "Middle Eastern Studies",
    "Molecular, Cell, and Developmental Biology",
    "Music",
    "Music Composition",
    "Music Education",
    "Music History and Industry",
    "Music Performance",
    "Musicology",
    "Neuroscience",
    "Nordic Studies",
    "Nursing",
    "Philosophy",
    "Physics",
    "Physiological Science",
    "Political Science",
    "Portuguese and Brazilian Studies",
    "Psychobiology",
    "Psychology",
    "Public Affairs",
    "Religion, Study of Russian Studies", 
    "Scandinavian Languages and Cultures", 
    "Sociology",
    "Spanish",
    "Spanish and Community and Culture",
    "Spanish and Linguistics",
    "Spanish and Portuguese",
    "Statistics",
    "Theater",
    "Theater and Performance Studies",
    "World Arts and Cultures"
]
let times = ["1:00 PM PST", "1:30 PM PST", "1:00 AM PST", "1:30 AM PST", 
            "2:00 PM PST", "2:30 PM PST", "2:00 AM PST", "2:30 AM PST", 
            "3:00 PM PST", "3:30 PM PST", "3:00 AM PST", "3:30 AM PST", 
            "4:00 PM PST", "4:30 PM PST", "4:00 AM PST", "4:30 AM PST", 
            "5:00 PM PST", "5:30 PM PST", "5:00 AM PST", "5:30 AM PST", 
            "6:00 PM PST", "6:30 PM PST", "6:00 AM PST", "6:30 AM PST", 
            "7:00 PM PST", "7:30 PM PST", "7:00 AM PST", "7:30 AM PST", 
            "8:00 PM PST", "8:30 PM PST", "8:00 AM PST", "8:30 AM PST", 
            "9:00 PM PST", "9:30 PM PST", "9:00 AM PST", "9:30 AM PST", 
            "10:00 PM PST", "10:30 PM PST", "10:00 AM PST", "10:30 AM PST",
             "11:00 PM PST", "11:30 PM PST", "11:00 AM PST", "11:30 AM PST", 
             "12:00 PM PST", "12:30 PM PST", "12:00 AM PST", "12:30 AM PST"
        ]        
let minGameTime = 20
let positions = [
    //corner
    <Corner icon={Go} />,
    <Property  color='#8E6A36' name='Kerckhoff' price='$60' />,
    <Property  name='Financial Aid Office' icon={FinAid} />,
    <Property  color='#8E6A36' name='Northern Lights' price='$60' />,
    <Property  name='USAC FEES' icon={USAC} price='PAY $200' />,
    <Property  name='Feast' price='$200' icon={Dining} />,
    <Property  color='#A8DDD7' name='Math Sciences' price='$100' />,
    <Property  name='Exuse Me Sir!' icon={Exuse_Me_Red} />,
    <Property  color='#A8DDD7' name='Engr. IV' price='$100' />,
    <Property  color='#A8DDD7' name='Boelter' price='$120' />,
    //corner
    <Corner icon={Jail}></Corner>,
    <Property  color='#EAACA3' name='Rolfe Hall' price='$140' />,
    <Property  name='Royce' icon={Royce} price='$150' />,
    <Property  color='#EAACA3' name='Schoenberg Music Hall' price='$140' />,
    <Property  color='#EAACA3' name='Dodd Hall' price='$160' />,
    <Property  name='De Neve' price='$200' icon={Dining} />,
    <Property  color='#F6B611' name='La Kretz' price='$180' />,
    <Property  name='Financial Aid Office' icon={FinAid} />,
    <Property  color='#F6B611' name='LS' price='$180' />,
    <Property  color='#F6B611' name='Young Hall' price='$200' />,
    //corner
    <Corner icon={NoFreeParking}></Corner>,
    <Property  color='#F15B45' name='ACKERMAN' price='$220' />,
    <Property  name='EXUSE ME SIR!' icon={Exuse_Me_Blue} />,
    <Property  color='#F15B45' name='WOODEN' price='$220' />,
    <Property  color='#F15B45' name='FRANZ' price='$240' />,
    <Property  name='BPLATE' price='$200' icon={Dining} />,
    <Property  color='#FFF261' name='BUNCHE' price='$260' />,
    <Property  color='#FFF261' name='KAPLAN' price='$260' />,
    <Property  name='POWELL' price='$150' icon={Powell} />,
    <Property  color='#FFF261' name='FRANZ' price='$280' />,
    //corner
    <Corner icon={GoToJail}></Corner>,
    <Property  color='#A8DC96' name='SCI & ENGR. LIBRARY' price='$300' />,
    <Property  name='Financial Aid Office' icon={FinAid} />,
    <Property  color='#A8DC96' name='BIOMED LIBRARY' price='$300' />,
    <Property  color='#A8DC96' name='YRL' price='$320' />,
    <Property  name='Covel' price='$200' icon={Dining} />,
    <Property  name='Exuse Me Sir!' icon={Exuse_Me_Yellow} />,
    <Property  color='#3F4CBB' name='Sculpture Garden' price='$350' />,
    <Property  name='Bruinbash Fest' icon={Concert} />,
    <Property  color='#3F4CBB' name='Fowler Museum' price='$400' />
]

export {majors, API_URL, times, minGameTime, positions}