
let API_URL = "http://localhost:3000"
let majors = ["Aerospace Engineering",
    "African American Studies",
    "African and Middle Eastern Studies",
    "American Indian Studies",
    "American Literature and Culture",
    "Ancient Near East and Egyptology",
    "Anthropology",
    "Applied Linguistics",
    "Applied Mathematics",
    "Arabic",
    "Architectural Studies",
    "Art",
    "Art History",
    "Asian American Studies",
    "Asian Humanities",
    "Asian Languages and Linguistics",
    "Asian Studies",
    "Asian Religions",
    "Atmospheric and Oceanic Sciences",
    "Atmospheric and Oceanic Sciences/Mathematics",
    "Astrophysics",
    "Biochemistry",
    "Bioengineering",
    "Biology",
    "Biophysics",
    "Business Economics",
    "Central and East European Languages and Cultures",
    "Chemical Engineering",
    "Chemistry",
    "Chemistry/Materials Science",
    "Chicana and Chicano Studies",
    "Chinese",
    "Classical Civilization",
    "Climate Science",
    "Civil Engineering",
    "Cognitive Science",
    "Communication",
    "Comparative Literature",
    "Computational and Systems Biology",
    "Computer Engineering",
    "Computer Science",
    "Computer Science and Engineering",
    "Computer Engineering",
    "Dance",
    "Data Theory",
    "Design | Media Arts",
    "Earth and Environmental Science",
    "Ecology, Behavior, and Evolution",
    "Economics",
    "Education and Social Transformation",
    "Electrical Engineering",
    "Engineering Geology",
    "English",
    "Environmental Science",
    "Ethnomusicology",
    "European Studies",
    "Film & Television",
    "Financial Actuarial Mathematics",
    "French",
    "French and Linguistics",
    "Gender Studies",
    "General Chemistry",
    "Geography",
    "Geography/Environmental Studies",
    "Geology",
    "Geophysics",
    "German",
    "Global Jazz Studies",
    "Global Studies",
    "Greek",
    "Greek and Latin",
    "History",
    "Human Biology and Society",
    "Individual Field BA Arts and Architecture",
    "Individual Field BA Theater, Film, and Television",
    "Individual Field of Concentration",
    "International Development Studies",
    "Iranian Studies",
    "Italian",
    "Italian and Special Fields",
    "Jewish Studies",
    "Korean",
    "Labor Studies",
    "Latin",
    "Latin American Studies",
    "Linguistics",
    "Linguistics and Anthropology",
    "Linguistics & Asian Languages & Cultures",
    "Linguistics and Computer Science",
    "Linguistics and English",
    "Linguistics and French",
    "Linguistics and Italian",
    "Linguistics and Philosophy",
    "Linguistics and Psychology",
    "Linguistics and Scandinavian Languages",
    "Linguistics and Spanish",
    "Manufacturing Engineering",
    "Marine Biology",
    "Materials Engineering",
    "Mathematics/Applied Science",
    "Mathematics/Economics",
    "Mathematics for Teaching",
    "Mathematics of Computation",
    "Mechanical Engineering",
    "Microbiology, Immunology, and Molecular Genetics",
    "Middle Eastern Studies",
    "Molecular, Cell, and Developmental Biology",
    "Music",
    "Music Composition",
    "Music Education",
    "Music History and Industry",
    "Music Performance",
    "Musicology",
    "Neuroscience",
    "Nordic Studies",
    "Nursing",
    "Philosophy",
    "Physics",
    "Physiological Science",
    "Political Science",
    "Portuguese and Brazilian Studies",
    "Psychobiology",
    "Psychology",
    "Public Affairs",
    "Religion, Study of Russian Studies", 
    "Scandinavian Languages and Cultures", 
    "Sociology",
    "Spanish",
    "Spanish and Community and Culture",
    "Spanish and Linguistics",
    "Spanish and Portuguese",
    "Statistics",
    "Theater",
    "Theater and Performance Studies",
    "World Arts and Cultures"
]
let times = ["1:00 PM PST", "1:30 PM PST", "1:00 AM PST", "1:30 AM PST", 
            "2:00 PM PST", "2:30 PM PST", "2:00 AM PST", "2:30 AM PST", 
            "3:00 PM PST", "3:30 PM PST", "3:00 AM PST", "3:30 AM PST", 
            "4:00 PM PST", "4:30 PM PST", "4:00 AM PST", "4:30 AM PST", 
            "5:00 PM PST", "5:30 PM PST", "5:00 AM PST", "5:30 AM PST", 
            "6:00 PM PST", "6:30 PM PST", "6:00 AM PST", "6:30 AM PST", 
            "7:00 PM PST", "7:30 PM PST", "7:00 AM PST", "7:30 AM PST", 
            "8:00 PM PST", "8:30 PM PST", "8:00 AM PST", "8:30 AM PST", 
            "9:00 PM PST", "9:30 PM PST", "9:00 AM PST", "9:30 AM PST", 
            "10:00 PM PST", "10:30 PM PST", "10:00 AM PST", "10:30 AM PST",
             "11:00 PM PST", "11:30 PM PST", "11:00 AM PST", "11:30 AM PST", 
             "12:00 PM PST", "12:30 PM PST", "12:00 AM PST", "12:30 AM PST"
        ]
let minGameTime = 20

export {majors, API_URL, times, minGameTime}